Repository AY2223S2-CS2113-F13-1/tp, pull requests merged in 2023-04, with the labels that each got.

#111 Add View by name and Junit Tests
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/exceptions/DuplicateRecipeNameException.java
  src/main/java/seedu/duke/exceptions/NoMatchingRecipeFound.java
  src/main/java/seedu/duke/recipe/RecipeList.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/StringLib.java
  src/main/java/seedu/duke/ui/UI.java
  src/test/java/seedu/duke/command/FindTest.java
  src/test/java/seedu/duke/command/ViewTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.Medium, severity.Low

#117 DG formatting fixes and Implements RecipeList as a Singleton
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/PlantUML/FindRecipe.png
  docs/PlantUML/FindRecipe.puml
  docs/PlantUML/RecipeFind.png
  docs/team/aungphonenaing.md
  docs/team/phone.jpg
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandType.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/recipe/RecipeList.java
  src/main/java/seedu/duke/recipe/StepList.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/FindTest.java
  src/test/java/seedu/duke/command/ViewTest.java
  src/test/java/seedu/duke/recipe/EditIngredientTest.java
  src/test/java/seedu/duke/recipe/EditStepTest.java
Labels: type.Enhancement, priority.Medium

#132 DG Improvements based on Javier's suggestions & Input filter for Add recipe feature
  docs/DeveloperGuide.md
  docs/PlantUML/ArchitectureInteract.png
  docs/PlantUML/ArchitectureInteract.puml
  docs/PlantUML/EditRecipeIngredients.png
  docs/PlantUML/EditRecipeIngredients.puml
  docs/PlantUML/EditRecipeSteps.png
  docs/PlantUML/EditRecipeSteps.puml
  docs/PlantUML/FindRecipe.png
  docs/PlantUML/FindRecipe.puml
  docs/PlantUML/Help.png
  docs/PlantUML/Help.puml
  docs/PlantUML/RecipeManage.png
  docs/PlantUML/RecipeManage.puml
  docs/PlantUML/RecipeManage_Add_List.png
  docs/PlantUML/RecipeManage_Add_List.puml
  docs/PlantUML/RecipeManage_Delete_Clear.png
  docs/PlantUML/RecipeManage_Delete_Clear.puml
  docs/PlantUML/RecipeView.png
  docs/PlantUML/RecipeView.puml
  docs/PlantUML/Recipe_View.png
  docs/UserGuide.md
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/exceptions/InvalidInputCharactersException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/recipe/RecipeList.java
  src/main/java/seedu/duke/ui/StringLib.java
  src/main/java/seedu/duke/ui/UI.java
  src/test/java/seedu/duke/command/ViewTest.java
  src/test/java/seedu/duke/parser/AddRecipeParserTest.java
Labels: type.Task, type.Bug, priority.High, severity.VeryLow

#139 UG Updates
  docs/README.md
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.VeryLow

#140 UG and Help command updates
  docs/UserGuide.md
  src/main/java/seedu/duke/ui/StringLib.java
  src/main/java/seedu/duke/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.Medium, severity.VeryLow

#142 Fix markdown bugs
  docs/UserGuide.md
Labels: severity.VeryLow

#143 insert missing ingredient edit implementation
  docs/DeveloperGuide.md
Labels: severity.VeryLow

#147 Step List Grammar update
  docs/UserGuide.md
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/recipe/StepList.java
  src/main/java/seedu/duke/ui/StringLib.java
  src/test/java/seedu/duke/recipe/EditStepTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.Medium, severity.VeryLow

#149 Fixes DG bugs on github pages
  docs/DeveloperGuide.md
Labels: severity.VeryLow

#150 Final UG and DG format fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: severity.VeryLow
